stages:
  - lint
  - test
  - Test_Build

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

license_scanning:
  only:
    refs:
      - tags
      - publish

dependency_scanning:
  only:
    refs:
      - tags
      - publish

.lint:
  stage: lint
  before_script:
    - pip install -U pip . -r requirements.txt bandit flake8 pylint
    - wget --quiet https://github.com/ianare/exif-samples/archive/master.tar.gz; tar -xzf master.tar.gz
  script:
    # Pylint throws many errors that need to work to fix
    #- pylint --rcfile=tox.ini EXIF.py ExifReader
    - flake8 EXIF.py ExifReader
    - bandit -r EXIF.py ExifReader
    - find exif-samples-master -name *.tiff -o -name *.jpg | xargs EXIF.py
    - find exif-samples-master -name *.tiff -o -name *.jpg | xargs EXIF.py -d

python-3.5-lint:
  extends: ".lint"
  image: python:3.5

python-3.6-lint:
  extends: ".lint"
  image: python:3.6

python-3.7-lint:
  extends: ".lint"
  image: python:3.7

python-3.8-lint:
  extends: ".lint"
  image: python:3.8

.build:
  stage: test
  artifacts:
    paths:
    - dist/
    - ExifReader.egg-info
  before_script:
    - pip install -U setuptools twine --quiet
  script:
    - python setup.py egg_info
    - python setup.py sdist bdist_wheel
    - python -m twine check dist/*

python-3.5-build:
  extends: ".build"
  image: python:3.5

python-3.6-build:
  extends: ".build"
  image: python:3.6

python-3.7-build:
  extends: ".build"
  image: python:3.7

python-3.8-build:
  extends: ".build"
  image: python:3.8

.test:
  stage: Test_Build
  before_script:
    - pip install -U pip --quiet
    - wget --quiet https://github.com/ianare/exif-samples/archive/master.tar.gz; tar -xzf master.tar.gz
  script:
    - pip install dist/*.whl
    - pip show -f ExifReader
    - find exif-samples-master -name *.tiff -o -name *.jpg | xargs EXIF.py
    - find exif-samples-master -name *.tiff -o -name *.jpg | xargs EXIF.py -d


python-3.5-test:
  extends: ".test"
  image: python:3.5

python-3.6-test:
  extends: ".test"
  image: python:3.6

python-3.7-test:
  extends: ".test"
  image: python:3.7

python-3.8-test:
  extends: ".test"
  image: python:3.8

Deploy_to_PyPi:
  image: python:3.7
  stage: Deploy
  variables:
    TWINE_USERNAME: $PYPI_USER
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  before_script:
    - pip install -U pip setuptools twine --quiet
  script:
    - python -m twine upload --verbose dist/*
  only:
    refs:
      - tags
      - publish
    variables:
      - $CI_COMMIT_TAG
